"""Ported from src/data/initialData.ts — fictional demo fixtures.

Only ever loaded on demand via POST /api/admin/reset-demo-data. A fresh production
database is intentionally left empty so real committee members never see fake pledges.
"""

from datetime import datetime, timedelta as _td, timezone

from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Announcement, EventDetails, PlannedExpense, RSVPRecord, SurveyResponse

EVENT_DETAILS_SEED = {
    "status": "Pending",
    "date": "Pending / For finalization",
    "time": "TBA (Target: 6:00 PM – 10:30 PM)",
    "venue": "Pending / For finalization",
    "venue_address": "Makati / BGC Area (Based on Survey Results)",
    "dress_code": "Smart Casual / Semi-Formal",
    "theme": "MakSci Batch 2007 Reunion & Homecoming",
    "notes": "Final date and venue contracts will be selected based on survey consensus.",
}

ANNOUNCEMENTS_SEED = [
    {
        "id": "ann-1",
        "title": "📢 MSHS Batch 2007: Official Planning Survey is Now Live!",
        "caption": "Calling all Makati Science High School Batch 2007 alumni! As we gear up for our milestone reunion, our planning committee needs your input. Please fill out the planning survey below so we can finalize our date, venue, activities, and budget.",
        "image_url": "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
        "tag": "Survey",
        "author": "Batch 2007 Core Committee",
        "date": "August 24, 2026",
        "is_pinned": True,
        "likes_count": 38,
    },
    {
        "id": "ann-2",
        "title": "📍 Venue & Date Scouting Update",
        "caption": "We are currently shortlisting potential venues (Makati / BGC hotel function hall, Intramuros rooftop events place, Tagaytay resort, and private dining places). Cast your vote in the survey so we can select the most accessible location and date for everyone including balikbayans!",
        "image_url": "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
        "tag": "Venue",
        "author": "Logistics Team",
        "date": "August 20, 2026",
        "is_pinned": False,
        "likes_count": 24,
    },
    {
        "id": "ann-3",
        "title": "💰 Transparent Batch Operating Funds Dashboard",
        "caption": "In true Makati Science transparency spirit, we have launched an open Operating Funds & Pledge tracking dashboard. All batch contributions, sponsorships, and planned expenditures will be reported here in real time with our live running balance.",
        "image_url": "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80",
        "tag": "Finance",
        "author": "Finance & Treasury Committee",
        "date": "August 18, 2026",
        "is_pinned": False,
        "likes_count": 31,
    },
]

EXPENSES_SEED = [
    {
        "id": "exp-1",
        "name": "Venue Reservation & Dinner Banquet (Est. 70 pax)",
        "category": "Venue & Banquet",
        "amount": 140000,
        "target_date": "2026-11-15",
        "status": "Quoted",
        "notes": "Estimated ₱2,000/head buffet banquet plus venue rental for 5 hours.",
    },
    {
        "id": "exp-2",
        "name": "Audio-Visual Lights, Sound System & LED Wall Display",
        "category": "Audio Visual & Lights",
        "amount": 25000,
        "target_date": "2026-11-15",
        "status": "Estimated",
        "notes": "For throwback slide presentation, batch tribute video, and open mic/band.",
    },
    {
        "id": "exp-3",
        "name": "Batch Souvenir Shirts & Commemorative Tokens",
        "category": "Souvenirs & T-Shirts",
        "amount": 35000,
        "target_date": "2026-10-30",
        "status": "Estimated",
        "notes": "Custom dri-fit batch shirts and engraved keepsake keychains / mugs.",
    },
    {
        "id": "exp-4",
        "name": "Official Photographer, Videographer & Photo Booth",
        "category": "Photo & Video",
        "amount": 20000,
        "target_date": "2026-11-15",
        "status": "Quoted",
        "notes": "Unlimited photo booth with magnetic prints + highlight reel coverage.",
    },
    {
        "id": "exp-5",
        "name": "Raffle Prizes, Batch Awards & Faculty Tokens",
        "category": "Prizes & Tokens",
        "amount": 18000,
        "target_date": "2026-11-01",
        "status": "Estimated",
        "notes": "Special tokens for beloved former MSHS teachers and fun batch trivia prizes.",
    },
    {
        "id": "exp-6",
        "name": "Stage Styling, Backdrop & Photo Wall",
        "category": "Decorations & Program",
        "amount": 15000,
        "target_date": "2026-11-15",
        "status": "Estimated",
        "notes": "MakSci Nostalgia throwback theme display and backdrop styling.",
    },
]

SURVEY_RESPONSES_SEED = [
    {
        "id": "resp-1",
        "full_name": "Maria Cristina Santos",
        "contact_number": "09171234567",
        "email": "mc.santos@gmail.com",
        "section2007": "IV-Curie",
        "attendance": "Yes, definitely!",
        "preferred_months": ["April", "December"],
        "specific_date_notes": "Any Saturday evening in April or December 2027 would be perfect!",
        "venue_suggestion": "The Blue Leaf Pavilion, Taguig",
        "preferred_venue_type": "Hotel / function room",
        "pledge_option": "₱5,000",
        "other_sponsorships": ["Prizes / raffle items", "Graphic design / invitations"],
        "other_sponsorship_details": "Can donate 2 units of gadgets for raffle and help design event logo.",
        "skills_offered": ["Graphic design / invitations", "Event planning / coordination"],
        "skills_details": "I work in creative brand management, happy to layout tickets and backdrops!",
        "nominated_organizer": "Events by Amanda Manila",
        "willing_to_organize": "Yes, I’d be happy to help!",
        "bringing_plus_one": "Yes, 1 +1",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Let’s invite our favorite Chemistry and Physics teachers as honored guests!",
        "pledge_paid_status": "Fully Paid",
    },
    {
        "id": "resp-2",
        "full_name": "Engr. Carlo Mendoza",
        "contact_number": "09189876543",
        "email": "carlo.mendoza@engineer.com",
        "section2007": "IV-Newton",
        "attendance": "Yes, definitely!",
        "preferred_months": ["December"],
        "specific_date_notes": "Mid-December 2027 so overseas batchmates can fly in for the holidays.",
        "venue_suggestion": "Crowne Plaza Galleria Manila / Ortigas",
        "preferred_venue_type": "Hotel / function room",
        "pledge_option": "₱10,000+",
        "custom_pledge_amount": "15000",
        "other_sponsorships": ["Financial sponsorship", "Drinks / refreshments"],
        "other_sponsorship_details": "Pledging ₱15,000 for main operations + sponsored craft beers/wine.",
        "skills_offered": ["Event planning / coordination", "Hosting / emceeing", "Accounting / budgeting"],
        "skills_details": "Happy to lead overall program committee and coordinate supplier contracts.",
        "nominated_organizer": "Makati Belle Events Management",
        "willing_to_organize": "Yes, I’d be happy to help!",
        "bringing_plus_one": "Yes, 1 +1",
        "bringing_kids": "Yes",
        "kids_count": 2,
        "other_suggestions": "Let’s prepare a throwback video compilation and photo gallery in the lobby.",
        "pledge_paid_status": "Partially Paid",
    },
    {
        "id": "resp-3",
        "full_name": "Dr. Katrina Beatrice Reyes",
        "contact_number": "09205557890",
        "email": "dr.kat.reyes@medcenter.ph",
        "section2007": "IV-Einstein",
        "attendance": "Most likely, but still confirming",
        "attendance_reason": "Checking hospital on-call schedule for 2027.",
        "preferred_months": ["April"],
        "specific_date_notes": "Saturday evening after Easter weekend.",
        "venue_suggestion": "Palacio de Maynila or Intramuros",
        "preferred_venue_type": "Restaurant / private dining",
        "pledge_option": "₱5,000",
        "other_sponsorships": ["Prizes / raffle items"],
        "other_sponsorship_details": "Donating gift certificates for batch wellness hamper.",
        "skills_offered": ["Program / activities", "Registration / guest management"],
        "skills_details": "Can help manage guest registration desk and table assignments.",
        "nominated_organizer": "Bella Vita Events & Productions",
        "willing_to_organize": "I can help occasionally",
        "bringing_plus_one": "No",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "A live acoustic band or batchmate jam session would be fantastic!",
        "pledge_paid_status": "Unpaid / Pledged",
    },
    {
        "id": "resp-4",
        "full_name": "Atty. Rafael Joaquin Dizon",
        "contact_number": "09176543210",
        "email": "atty.dizon@lawfirm.ph",
        "section2007": "IV-Dalton",
        "attendance": "Yes, definitely!",
        "preferred_months": ["April", "December"],
        "specific_date_notes": "April 24 or December 18, 2027",
        "venue_suggestion": "Club Filipino, Greenhills",
        "preferred_venue_type": "Private house / events place",
        "pledge_option": "Custom Amount",
        "custom_pledge_amount": "7500",
        "other_sponsorships": ["Printing / souvenirs", "Prizes / raffle items"],
        "other_sponsorship_details": "Can sponsor printed keepsake yearbooks and custom batch lanyards.",
        "skills_offered": ["Hosting / emceeing", "Social media / communications"],
        "skills_details": "Experienced host/emcee, ready to host the formal program and games!",
        "nominated_organizer": "Grand Milestones Events Agency",
        "willing_to_organize": "Yes, I’d be happy to help!",
        "bringing_plus_one": "Yes, 1 +1",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Trivia contest about our high school teachers and classic MSHS moments.",
        "pledge_paid_status": "Fully Paid",
    },
    {
        "id": "resp-5",
        "full_name": "Patricia Marie Alcantara",
        "contact_number": "09281239876",
        "email": "pat.alcantara@studio.com",
        "section2007": "IV-Darwin",
        "attendance": "Yes, definitely!",
        "preferred_months": ["April", "December"],
        "specific_date_notes": "Any weekend in April or December 2027",
        "venue_suggestion": "MSHS Campus Grounds & Rooftop Hall",
        "preferred_venue_type": "School / campus",
        "pledge_option": "₱3,000",
        "other_sponsorships": ["Photography / videography"],
        "other_sponsorship_details": "Providing pro photo coverage and edited 4k video montage.",
        "skills_offered": ["Photography / videography", "Technical / sound & lights"],
        "skills_details": "I own a multimedia studio, we will handle multi-cam video shoot!",
        "nominated_organizer": "The Concept Events Studio",
        "willing_to_organize": "Maybe, depending on what’s needed",
        "bringing_plus_one": "No",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Let’s do a quick morning campus visit followed by evening grand banquet.",
        "pledge_paid_status": "Unpaid / Pledged",
    },
    {
        "id": "resp-6",
        "full_name": "Gian Paolo Ramos",
        "contact_number": "09081122334",
        "email": "gian.ramos@techcorp.io",
        "section2007": "IV-Curie",
        "attendance": "Not sure yet",
        "attendance_reason": "Depends on work travel schedule in 2027.",
        "preferred_months": ["December"],
        "specific_date_notes": "Around Dec 15-22, 2027",
        "venue_suggestion": "Resort in Antipolo / Rizal",
        "preferred_venue_type": "Resort / outdoor venue",
        "pledge_option": "₱2,000",
        "other_sponsorships": ["None for now"],
        "skills_offered": ["I’d prefer to just attend 😊"],
        "nominated_organizer": "Urban Eventive Co.",
        "willing_to_organize": "I’d prefer not to be involved in organizing",
        "bringing_plus_one": "Not sure yet",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Make sure there is high-speed WiFi and live stream for batchmates overseas.",
        "pledge_paid_status": "Unpaid / Pledged",
    },
    {
        "id": "resp-7",
        "full_name": "Sheryl Anne Tan-Lim",
        "contact_number": "09198765432",
        "email": "sheryl.tan@culinary.ph",
        "section2007": "IV-Newton",
        "attendance": "Yes, definitely!",
        "preferred_months": ["April"],
        "specific_date_notes": "Saturday in late April 2027",
        "venue_suggestion": "Glasshouse at Greenbelt or BGC High Street",
        "preferred_venue_type": "Restaurant / private dining",
        "pledge_option": "Custom Amount",
        "custom_pledge_amount": "12500",
        "other_sponsorships": ["Food / catering", "Drinks / refreshments"],
        "other_sponsorship_details": "Sponsoring custom dessert bar and 2-tiered reunion cake!",
        "skills_offered": ["Food / catering", "Sourcing suppliers / venue"],
        "skills_details": "I run a pastry and catering kitchen, can supply pastries and manage tasting.",
        "nominated_organizer": "Viva Events & Productions",
        "willing_to_organize": "Yes, I’d be happy to help!",
        "bringing_plus_one": "Yes, 1 +1",
        "bringing_kids": "Yes",
        "kids_count": 1,
        "other_suggestions": "Provide a kids play corner or quiet area so parents can mingle easily.",
        "pledge_paid_status": "Fully Paid",
    },
    {
        "id": "resp-8",
        "full_name": "Mark Dennis Fernandez",
        "contact_number": "09156789012",
        "email": "dennis.f@sgconsulting.com",
        "section2007": "IV-Einstein",
        "attendance": "Yes, definitely!",
        "preferred_months": ["December"],
        "specific_date_notes": "December 18-24, 2027 (Returning from Singapore for Christmas holidays)",
        "venue_suggestion": "Manila Hotel Champagne Room or Centennial Hall",
        "preferred_venue_type": "Hotel / function room",
        "pledge_option": "₱10,000+",
        "custom_pledge_amount": "20000",
        "other_sponsorships": ["Financial sponsorship", "Event equipment / sound system"],
        "other_sponsorship_details": "Pledging ₱20k towards audio-visual setup and teacher stipends.",
        "skills_offered": ["Music / DJ", "Technical / sound & lights"],
        "skills_details": "I do DJing as a hobby, will prepare our 2000s throwback playlist!",
        "nominated_organizer": "Sound & Stage Event Planners",
        "willing_to_organize": "Yes, I’d be happy to help!",
        "bringing_plus_one": "Yes, 1 +1",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Let’s play classic 2000s OPM and rock anthems we used to listen to in high school.",
        "pledge_paid_status": "Fully Paid",
    },
    {
        "id": "resp-9",
        "full_name": "Joanna Rose Perez",
        "contact_number": "09224466880",
        "email": "joanna.perez@gov.ph",
        "section2007": "IV-Dalton",
        "attendance": "Unfortunately, I won’t be able to attend",
        "attendance_reason": "Will be in the US for graduate school fellowship during 2027.",
        "preferred_months": ["April", "December"],
        "preferred_venue_type": "Hotel / function room",
        "pledge_option": "₱2,000",
        "other_sponsorships": ["Prizes / raffle items"],
        "other_sponsorship_details": "Still want to support the batch funds even though I cannot attend physically!",
        "skills_offered": ["Social media / communications"],
        "skills_details": "Can help manage the batch Facebook / IG page and post live updates.",
        "nominated_organizer": "Events by Amanda Manila",
        "willing_to_organize": "I can help occasionally",
        "bringing_plus_one": "No",
        "bringing_kids": "No",
        "kids_count": 0,
        "other_suggestions": "Please set up a Zoom / YouTube private live stream for batchmates abroad!",
        "pledge_paid_status": "Fully Paid",
    },
]

RSVPS_SEED = [
    {
        "id": "rsvp-1",
        "full_name": "Maria Cristina Santos",
        "contact_number": "09171234567",
        "email": "mc.santos@gmail.com",
        "status": "Attending",
        "bringing_plus_one": True,
        "kids_count": 0,
        "dietary_restrictions": "Pescatarian",
        "message_to_batch": "Can’t wait to see everyone after so many years! 🧪✨",
    },
    {
        "id": "rsvp-2",
        "full_name": "Engr. Carlo Mendoza",
        "contact_number": "09189876543",
        "email": "carlo.mendoza@engineer.com",
        "status": "Attending",
        "bringing_plus_one": True,
        "kids_count": 2,
        "dietary_restrictions": "None",
        "message_to_batch": "Let’s make our 2007 reunion one for the history books! 🔬",
    },
    {
        "id": "rsvp-3",
        "full_name": "Dr. Katrina Beatrice Reyes",
        "contact_number": "09205557890",
        "email": "dr.kat.reyes@medcenter.ph",
        "status": "Maybe",
        "bringing_plus_one": False,
        "kids_count": 0,
        "dietary_restrictions": "No beef",
        "message_to_batch": "Hoping the hospital roster permits! So excited!",
    },
    {
        "id": "rsvp-4",
        "full_name": "Atty. Rafael Joaquin Dizon",
        "contact_number": "09176543210",
        "email": "atty.dizon@lawfirm.ph",
        "status": "Attending",
        "bringing_plus_one": True,
        "kids_count": 0,
        "dietary_restrictions": "None",
        "message_to_batch": "Prepared my high school throwback stories already haha!",
    },
    {
        "id": "rsvp-5",
        "full_name": "Patricia Marie Alcantara",
        "contact_number": "09281239876",
        "email": "pat.alcantara@studio.com",
        "status": "Attending",
        "bringing_plus_one": False,
        "kids_count": 0,
        "dietary_restrictions": "No seafood",
        "message_to_batch": "Bringing studio gear for portrait sessions!",
    },
    {
        "id": "rsvp-6",
        "full_name": "Sheryl Anne Tan-Lim",
        "contact_number": "09198765432",
        "email": "sheryl.tan@culinary.ph",
        "status": "Attending",
        "bringing_plus_one": True,
        "kids_count": 1,
        "dietary_restrictions": "None",
        "message_to_batch": "Cake is on me! See you batchmates ❤️",
    },
    {
        "id": "rsvp-7",
        "full_name": "Mark Dennis Fernandez",
        "contact_number": "09156789012",
        "email": "dennis.f@sgconsulting.com",
        "status": "Attending",
        "bringing_plus_one": True,
        "kids_count": 0,
        "dietary_restrictions": "None",
        "message_to_batch": "Flying home for this! Countdown begins!",
    },
]


async def reset_demo_data(session: AsyncSession) -> None:
    from app.pledge import parse_pledge_amount

    await session.execute(delete(SurveyResponse))
    await session.execute(delete(RSVPRecord))
    await session.execute(delete(Announcement))
    await session.execute(delete(PlannedExpense))
    await session.execute(delete(EventDetails))

    now = datetime.now(timezone.utc)

    session.add(EventDetails(id=EventDetails.SINGLETON_ID, updated_at=now, **EVENT_DETAILS_SEED))

    for offset, row in enumerate(ANNOUNCEMENTS_SEED):
        # Preserve seed list order (newest first) regardless of insert order.
        session.add(Announcement(created_at=now.replace(microsecond=0) - _td(minutes=offset), **row))

    for row in EXPENSES_SEED:
        session.add(PlannedExpense(updated_at=now, **row))

    for row in SURVEY_RESPONSES_SEED:
        row = dict(row)
        row["computed_pledge_amount"] = parse_pledge_amount(
            row["pledge_option"], row.get("custom_pledge_amount")
        )
        session.add(SurveyResponse(submitted_at=now, **row))

    for row in RSVPS_SEED:
        session.add(RSVPRecord(submitted_at=now, **row))

    await session.commit()
